services:
  my-gpt:
    image: savantly/base-bot:latest
    ports:
      - 9000:9000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_NAME: "my-demo"
      PINECONE_ENV: ${PINECONE_ENV}
      SAVANTLY_CHAT_VECTORSTORE_CREATE_IF_MISSING: "False"
#     SAVANTLY_CHAT_<other-settting>: "value"
    volumes:
      - ./data/docs:/app/data/docs
      - ./src/settings.py:/app/settings.py
      - ./data/stores:/app/data/stores

