---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-bot.fullname" . }}
  labels:
    {{- include "base-bot.labels" . | nindent 4 }}
data:
  settings.py: |
  {{- toYaml .Values.chat_settings | nindent 4 }}