---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-bot.fullname" . }}
  labels:
    {{- include "base-bot.labels" . | nindent 4 }}
data:
  settings.py: |
    REPHRASE_PROMPT = """
    {{- .Values.chat_settings.rephrase_prompt | nindent 4 }}
    """
    QA_PROMPT = """
    {{- .Values.chat_settings.qa_prompt | nindent 4 }}
    """
    {{- toYaml .Values.chat_settings.additional | nindent 4 }}