services:
  simple-base-bot:
    image: my-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./custom/vectorstore.py:/app/base_bot/vectorstore.py
      - ./data/docs:/app/data/docs
      - ./data/stores:/app/data/stores

